parameters:

services:
  _defaults:
    autoconfigure: true
    autowire: true

  # Load Services
  Bolge\App\Service\:
    resource: '../App/Service'
    public: true

  # Load Transformers
  Bolge\App\Dto\Response\Transformer\:
    resource: '../App/Dto/Response/Transformer'

  # Load Controllers
  Bolge\App\Controller\:
    resource: '../App/Controller/'
    public: true
  
  # Load Event Subscribers
  Bolge\App\EventSubscriber\:
    resource: '../App/EventSubscriber'
    public: true  

  # Load Event Dispatcher
  Symfony\Component\EventDispatcher\EventDispatcherInterface:
    public: true
    class: Symfony\Component\EventDispatcher\EventDispatcher
    # Call Subscribers
    calls:
      - addSubscriber: ['@Bolge\App\EventSubscriber\WordpressAdminSubscriber']
      - addSubscriber: ['@Bolge\App\EventSubscriber\WordpressFrontSubscriber']


